name: Update compressed bins

on:
  push:
    branches:
      - main         # adjust if your default branch is not "main"
  schedule:
    - cron: "0 0 * * 0"   # every Sunday at 00:00 UTC
  workflow_dispatch:       # still allow manual runs

jobs:
  build-and-compress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libzstd-dev

      - name: Clone and build PCC
        run: |
          git clone https://github.com/filrg/pcc
          cd pcc
          cmake -S . -B build -D pcc_DEVELOPER_MODE=TRUE
          cmake --build build -j$(nproc)

      - name: Run compression
        run: |
          bash run.sh longdress

      - name: Recreate filrg-pcc-compressed with only bins
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # start clean tree from main
          git checkout --orphan filrg-pcc-compressed
          git reset --hard
          git rm -rf . >/dev/null 2>&1 || true

          # move bins to root
          mv compressed/*.bin ./ || true
          rm -rf compressed

          # add and commit
          if ls *.bin 1> /dev/null 2>&1; then
            git add *.bin
            git commit -m "Regenerated compressed binaries"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git filrg-pcc-compressed --force
          fi

