name: Update compressed bins

on:
  workflow_dispatch:

jobs:
  build-and-compress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libzstd-dev

      - name: Clone and build PCC
        run: |
          git clone https://github.com/filrg/pcc
          cd pcc
          cmake -S . -B build -D pcc_DEVELOPER_MODE=TRUE
          cmake --build build -j$(nproc)

      - name: Run compression
        run: |
          bash run.sh longdress

      - name: Create branch and commit bins
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # create orphan branch (no history, no files)
          git checkout --orphan filrg-pcc-compressed
          git rm -rf . >/dev/null 2>&1 || true

          # move bins to repo root
          mv compressed/*.bin ./
          rm -rf compressed

          # add only bin files
          git add *.bin

          git commit -m "Add compressed binaries only"
          # commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Update compressed binaries"
            git push origin filrg-pcc-compressed --force
          fi
